---
- name: Install Git 1.7.1
  yum: name=git state=present
  
- name: Install Tomcat 7.0.33
  yum: name=tomcat state=present
  
- name: Configure Tomcat server
  template: src=server.xml.j2 dest=/usr/share/tomcat/conf/server.xml
  notify: restart tomcat
