---
- name: Install Git 1.7.1
  yum: name=git state=present
  
- name: Install Tomcat 7.0.33
  yum: name=tomcat state=present

- name: add group "tomcat"
  group: name=tomcat

- name: add user "tomcat"
  user: name=tomcat group=tomcat home=/usr/share/tomcat

- name: Change ownership of Tomcat installation
  file: path=/usr/share/tomcat/ mode=0755 owner=tomcat group=tomcat state=directory recurse=yes

- name: Configure Tomcat server
  template: src=server.xml.j2 dest=/usr/share/tomcat/conf/server.xml
  notify: restart tomcat
